### ISSUE TITLE
[nodemon] starting `node dist/server/index.js`

### ISSUE THREAD

**Issue by smith64fx** [qdouble/angular2webpack2-starter#69]
Hey there!

I get this error when I try to start with "npm run universal"

```
/Users/smith/Git/angular2webpack2-starter/dist/server/index.js:4
encapsulation:o.ViewEncapsulation.None}),a("design:paramtypes",[])],t)}(),l=function(){function t(){}return t=r([n.i(o.Directive)({selector:"[md-list-avatar]"}),a("design:paramtypes",[])],t)}(),c=function(){function t(t,e){this._renderer=t,this._element=e,this._hasFocus=!1}return Object.defineProperty(t.prototype,"_hasAvatar",{set:function(t){this._renderer.setElementClass(this._element.nativeElement,"md-list-avatar",null!=t)},enumerable:!0,configurable:!0}),t.prototype.ngAfterContentInit=function(){this._lineSetter=new i.e(this._lines,this._renderer,this._element)},t.prototype._handleFocus=function(){this._hasFocus=!0},t.prototype._handleBlur=function(){this._hasFocus=!1},r([n.i(o.ContentChildren)(i.f),a("design:type",o.QueryList)],t.prototype,"_lines",void 0),r([n.i(o.ContentChild)(l),a("design:type",l),a("design:paramtypes",[l])],t.prototype,"_hasAvatar",null),t=r([n.i(o.Component)({selector:"md-list-item, a[md-list-item]",host:{role:"listi

TypeError: ["logger","both"].includes is not a function
    at Object.module.exports.t../src/app/reducers/index.ts (/Users/smith/Git/angular2webpack2-starter/dist/server/index.js:4:31318)
    at e (/Users/smith/Git/angular2webpack2-starter/dist/server/index.js:1:177)
    at Object.module.exports.t../src/app/app.imports.ts (/Users/smith/Git/angular2webpack2-starter/dist/server/index.js:4:25139)
    at e (/Users/smith/Git/angular2webpack2-starter/dist/server/index.js:1:177)
    at Object.module.exports.t../src/app/app.module.universal.node.ts (/Users/smith/Git/angular2webpack2-starter/dist/server/index.js:4:25740)
    at e (/Users/smith/Git/angular2webpack2-starter/dist/server/index.js:1:177)
    at Object.<anonymous> (/Users/smith/Git/angular2webpack2-starter/dist/server/index.js:5:3504)
    at Object.module.exports.t../src/server.ts (/Users/smith/Git/angular2webpack2-starter/dist/server/index.js:5:4278)
    at e (/Users/smith/Git/angular2webpack2-starter/dist/server/index.js:1:177)
    at /Users/smith/Git/angular2webpack2-starter/dist/server/index.js:1:785
[nodemon] app crashed - waiting for file changes before starting...
```

any idea?

**Comment by qdouble** [comment]
@smith64fx is this a clean install? did you alter the tsconfig or any files?

**Comment by qdouble** [comment]
@smith64fx if @core-js types are install, includes should be recognized as a function... make sure to run `npm install` if you're switching between branches that didn't include Universal. If you're still having an issue beyond that, just let me know and I'll re-open.

**Comment by phil-lgr** [comment]
Hey, first of, thank you for your effort, great starter :)

I run in the same error with node 5.2.0 on windows from a clean install, do you recommend a particular node v ?

**Comment by qdouble** [comment]
@phil-lgr I'm using node 6.5 locally so you could try that...also, is core-js types installed?
